import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Privacy Policy - Festi",
  description:
    "How Festi collects, uses, and protects your personal data in accordance with the GDPR.",
};

const LAST_UPDATED = "15 July 2026";

export default function PrivacyPolicyPage() {
  return (
    <main className="mx-auto max-w-3xl px-4 py-16 sm:py-24">
      <div className="mb-10">
        <Link
          href="/"
          className="text-sm text-primary hover:text-primary-hover"
        >
          &larr; Back to home
        </Link>
      </div>

      <article className="space-y-8 text-muted-foreground">
        <header className="space-y-2">
          <h1 className="text-3xl font-bold tracking-tight text-foreground sm:text-4xl">
            Privacy Policy
          </h1>
          <p className="text-sm">Last updated: {LAST_UPDATED}</p>
        </header>

        <Section title="1. Who we are">
          <p>
            Festi (&quot;we&quot;, &quot;us&quot;, &quot;our&quot;) is a cycling
            community platform where riders can create a profile, plan and share
            rides and routes, form groups, and connect with other cyclists. It
            is open to anyone with a valid email address. If you have questions
            about this policy, contact us at{" "}
            <a
              href="mailto:info@festicycling.com"
              className="text-primary hover:text-primary-hover"
            >
              info@festicycling.com
            </a>
            .
          </p>
        </Section>

        <Section title="2. Data we collect">
          <p>
            We collect only the data you provide or that is generated by your
            use of the service:
          </p>
          <ul className="list-disc space-y-1 pl-6">
            <li>
              <strong>Account information</strong> &mdash; your name, username,
              and email address when you register, together with a securely
              hashed password.
            </li>
            <li>
              <strong>Profile image</strong> &mdash; an optional avatar you
              upload in your profile. Uploaded images are processed in your
              browser (resized and converted to WebP) and stored in our object
              storage.
            </li>
            <li>
              <strong>Account status</strong> &mdash; a role field (
              <em>user</em> or <em>admin</em>) and, if applicable, a ban record
              including reason and expiry date, managed by site administrators.
            </li>
            <li>
              <strong>Session data</strong> &mdash; authentication tokens, IP
              address, and browser type stored per active session. If an
              administrator uses the impersonation feature, that session is
              flagged with the administrator&apos;s ID for audit purposes.
            </li>
            <li>
              <strong>Community &amp; content data</strong> &mdash; groups,
              rides, routes and start locations, group and direct messages,
              follows, and notifications you create or generate.
            </li>
            <li>
              <strong>Activity &amp; usage data</strong> &mdash; an activity log
              of key actions (e.g. logins, registrations, group and ride events)
              including IP address, browser type, and timestamps, retained for
              security and debugging purposes.
            </li>
          </ul>
          <p>We do not collect payment information. Festi is free to use.</p>
        </Section>

        <Section title="3. How we use your data">
          <ul className="list-disc space-y-1 pl-6">
            <li>To provide, maintain, and improve the service.</li>
            <li>To authenticate you and keep your account secure.</li>
            <li>
              To display your uploaded profile and group images from our object
              storage.
            </li>
            <li>
              To plan and display rides and routes &mdash; when you use the map
              and route planner, the coordinates you select are sent to our map
              tile and routing providers (see &sect;5) to render maps and
              calculate routes.
            </li>
            <li>
              To send transactional emails (e.g. email verification, password
              reset) via our email provider. We do not send marketing emails
              without your explicit consent.
            </li>
            <li>
              To protect against abuse &mdash; rate limiting is applied to
              sensitive endpoints, and request metadata is logged to prevent
              brute-force attacks and misuse.
            </li>
            <li>
              To enforce platform rules &mdash; administrators may view account
              status, ban abusive accounts, and in exceptional support cases
              impersonate an account. All impersonated sessions are logged and
              attributable to the acting administrator.
            </li>
          </ul>
        </Section>

        <Section title="4. Legal basis (GDPR)">
          <p>
            If you are located in the European Economic Area, we process your
            data under the following legal bases:
          </p>
          <ul className="list-disc space-y-1 pl-6">
            <li>
              <strong>Contract</strong> &mdash; processing necessary to provide
              the service you signed up for, including account management and
              transactional emails (Art. 6(1)(b) GDPR).
            </li>
            <li>
              <strong>Legitimate interests</strong> &mdash; security logging,
              abuse prevention, and platform integrity (Art. 6(1)(f) GDPR).
            </li>
            <li>
              <strong>Consent</strong> &mdash; any optional processing that
              relies on your consent (Art. 6(1)(a) GDPR). You may withdraw
              consent at any time; withdrawal does not affect the lawfulness of
              processing before withdrawal.
            </li>
          </ul>
        </Section>

        <Section title="5. Third-party services">
          <p>We use the following sub-processors:</p>
          <div className="space-y-4">
            <Subprocessor
              name="Cloudflare, Inc."
              purpose="Hosting, content delivery, and image storage (Cloudflare R2). Cloudflare may log IP addresses and request metadata for security and reliability."
              location="USA / global edge network"
              href="https://www.cloudflare.com/privacypolicy/"
            />
            <Subprocessor
              name="Neon (PostgreSQL)"
              purpose="Database hosting for your account and community data."
              location="EU (Frankfurt)"
              href="https://neon.tech/privacy-policy"
            />
            <Subprocessor
              name="Resend"
              purpose="Transactional email delivery (verification, password reset)."
              location="USA"
              href="https://resend.com/legal/privacy-policy"
            />
            <Subprocessor
              name="MapTiler"
              purpose="Map tiles for the ride map. Coordinates of the map view are sent to render tiles."
              location="EU (Switzerland)"
              href="https://www.maptiler.com/privacy-policy/"
            />
            <Subprocessor
              name="OpenFreeMap"
              purpose="Fallback map tiles when no MapTiler key is configured."
              location="EU"
              href="https://openfreemap.org/"
            />
            <Subprocessor
              name="BRouter"
              purpose="Route calculation for the ride planner. Selected waypoint coordinates are sent to compute routes."
              location="EU (Germany)"
              href="https://brouter.de/"
            />
          </div>
          <p>
            Each provider is bound by their own privacy policy and, where
            applicable, standard contractual clauses under GDPR. Where a
            provider processes data outside the EU/EEA, we rely on appropriate
            safeguards such as the EU Standard Contractual Clauses.
          </p>
        </Section>

        <Section title="6. Data retention">
          <p>
            We retain your account and community data for as long as your
            account is active. When you delete your account, your personal data
            (including uploaded images) is removed. Anonymised, aggregated
            statistics may be retained. Server and activity logs are kept only
            as long as necessary for security and debugging.
          </p>
        </Section>

        <Section title="7. Your rights">
          <p>Depending on your jurisdiction, you may have the right to:</p>
          <ul className="list-disc space-y-1 pl-6">
            <li>access the personal data we hold about you (Art. 15);</li>
            <li>correct inaccurate data (Art. 16);</li>
            <li>
              request deletion of your data &mdash; the &quot;right to be
              forgotten&quot; (Art. 17);
            </li>
            <li>object to or restrict certain processing (Art. 18, 21);</li>
            <li>
              data portability &mdash; receive your data in a machine-readable
              format (Art. 20).
            </li>
          </ul>
          <p>
            To exercise any of these rights, email{" "}
            <a
              href="mailto:info@festicycling.com"
              className="text-primary hover:text-primary-hover"
            >
              info@festicycling.com
            </a>
            . We will respond within 30 days. You also have the right to lodge a
            complaint with a supervisory authority (Art. 77 GDPR), for example
            the data protection authority of your German federal state.
          </p>
        </Section>

        <Section title="8. Cookies &amp; local storage">
          <p>
            Festi uses only strictly necessary cookies. Session cookies are used
            solely for authentication and expire when you sign out or after the
            session lifetime (7 days). These do not require consent under &sect;
            25(2) TTDSG. We also use browser local storage to remember your
            cookie notice preference. We do not use third-party advertising or
            cross-site tracking cookies.
          </p>
        </Section>

        <Section title="9. Security">
          <p>
            Passwords are never stored in plain text &mdash; they are stored as
            a secure cryptographic hash. All data in transit is encrypted via
            HTTPS/TLS. We apply rate limiting on sensitive endpoints to prevent
            brute-force attacks. Administrator actions (role changes, bans,
            impersonation) are restricted to authenticated admin accounts, and
            all impersonated sessions are logged.
          </p>
        </Section>

        <Section title="10. Children's privacy">
          <p>
            Festi is not directed at children under 16. We do not knowingly
            collect personal data from children. If you believe a child has
            created an account, please contact us so we can delete it.
          </p>
        </Section>

        <Section title="11. Changes to this policy">
          <p>
            We may update this policy from time to time. We will notify you of
            significant changes by updating the &quot;Last updated&quot; date
            above. Continued use of the service after changes constitutes
            acceptance of the revised policy.
          </p>
        </Section>

        <Section title="12. Contact">
          <p>
            Questions or concerns about this policy? Reach us at{" "}
            <a
              href="mailto:info@festicycling.com"
              className="text-primary hover:text-primary-hover"
            >
              info@festicycling.com
            </a>
            .
          </p>
        </Section>
      </article>
    </main>
  );
}

function Section({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <section className="space-y-3">
      <h2 className="text-xl font-semibold text-foreground">{title}</h2>
      {children}
    </section>
  );
}

function Subprocessor({
  name,
  purpose,
  location,
  href,
}: {
  name: string;
  purpose: string;
  location: string;
  href: string;
}) {
  return (
    <div className="rounded-lg border border-border bg-card/50 p-4">
      <p className="font-medium text-foreground">{name}</p>
      <p className="mt-1 text-sm">{purpose}</p>
      <p className="mt-2 text-sm">
        Location: {location} &middot;{" "}
        <a
          href={href}
          target="_blank"
          rel="noopener noreferrer"
          className="text-primary hover:text-primary-hover"
        >
          Privacy policy
        </a>
      </p>
    </div>
  );
}
